modLoader = "javafml"
loaderVersion = "[42,)"
issueTrackerURL = "https://github.com/trikzon/shuffle/issues"
license = "MIT; Assets licensed as All Rights Reserved"

[[mods]]
modId = "shuffle"
version = "${version}"
displayName = "Shuffle"
authors = "Trikzon"
description = '''
Place random blocks from your hotbar with ease!
'''
#logoFile = ""

[[dependencies.shuffle]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shuffle]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"
