modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/Trikzon/shuffle/issues" #optional

[[mods]] #mandatory
modId="shuffle" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Shuffle" #mandatory
#updateJSONURL="" #optional
displayURL="https://modrinth.com/mod/shuffle" #optional
logoFile="assets/shuffle/icon.png" #optional
#credits="" #optional
authors="Trikzon" #optional
description='''
Randomly place blocks from your hotbar while building.
'''

[[dependencies.shuffle]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.shuffle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.shuffle]]
    modId="ash_api"
    mandatory=true
    versionRange="[2.1.0,3.0.0-alpha.1)"
    ordering="NONE"
    side="BOTH"
